# ----
# Site

title: Axel Coaching
url: "https://www.axelcoaching.com.au"
baseurl: ""
google_analytics_key:
google_maps_javascript_api_key:
snipcart_api_key: YTg5MDNkMmItZmIyOC00YWZhLWE5MzctYWE2M2VhNDkxOGI2NjM2NTMzMDAzNDQzMDgwNTc5

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: 
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: 
  links:
    - 

# -----
# Build

paginate: 10
paginate_path: "/advice/:num/"

collections:
  services:
    output: true
  testimonials:

defaults:
  -
    scope:
      path: ""
    values:
      layout: page
      background_image_path: /images/axelcoaching.png
      image: /images/axelcoaching.png
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      _options:
        content:
          width: 960
          height: 2000
      _comments:
        image: Shown in social shares and the advice list.
  -
    scope:
      path: ""
      type: "testimonials"
    values:
      _options:
        image:
          width: 440
          height: 440

  -
    scope:
      path: ""
      type: "services"
    values:
      layout: service
      _options:
        image:
          width: 440
          height: 440

permalink: pretty

jekyll-archives:
  enabled:
    - categories

gems:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

call_to_actions:
  - Contact
  - Advice
  - Map

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS

_comments:
  large_header: Toggles the size of the top banner.
  show_in_navigation: Toggles a link in the top banner.
  author_staff_member: The staff member writing this post.
  call_to_action: Type of request shown at the bottom of this page.
  background_image_path: Image shown in the top banner, blank for the default.
  testimonials: Update, add or remove testimonials.
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  phone_extension: The digits after dialing the company phone.
  credentials: Shown as subtext on staff member summaries.
  contact_email_address: Address for the contact form to send to.
  new_window: Whether the link opens a new browser tab/window.
