# ----
# Site

title: Axel Coaching
url: "https://www.axelcoaching.com.au"
baseurl: ""
google_analytics_key:
google_maps_javascript_api_key:
snipcart_api_key: YTg5MDNkMmItZmIyOC00YWZhLWE5MzctYWE2M2VhNDkxOGI2NjM2NTMzMDAzNDQzMDgwNTc5

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: 
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: 
  links:
    - 

# -----
# Build

paginate: 10
paginate_path: "/advice/:num/"

collections:
  services:
    output: true
  testimonials:
  products:

defaults:
  -
    scope:
      path: ""
    values:
      layout: page
      background_image_path: /images/axelcoaching.png
      image: /images/axelcoaching.png
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      _options:
        content:
          width: 960
          height: 2000
      _comments:
        image: Shown in social shares and the advice list.
  -
    scope:
      path: ""
      type: "testimonials"
    values:
      _options:
        image:
          width: 440
          height: 440

  -
    scope:
      path: ""
      type: "services"
    values:
      layout: service
      _options:
        image:
          width: 440
          height: 440

permalink: pretty

jekyll-archives:
  enabled:
    - categories

gems:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

call_to_actions:
  - Contact
  - Map

social_icons:
  - Facebook
  - LinkedIn
