backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "uploads" # Media files will be stored in the repo under uploads
collections:
  - name: "services" # Used in routes, e.g., /admin/collections/services
    label: "Services" # Used in the UI
    folder: "_services/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Position", name: "position", widget: "number", valueType: 'int'}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "products" # Used in routes, e.g., /admin/collections/products
    label: "Products" # Used in the UI
    folder: "_products/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Label", name: "label", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Price", name: "price", widget: "number", valueType: 'int'}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "testimonials" # Used in routes, e.g., /admin/collections/testimonials
    label: "Testimonials" # Used in the UI
    folder: "_testimonials/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Image", name: "image", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}